# Generated by Django 4.0.3 on 2022-03-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='couple_consultation_duration',
        ),
        migrations.RemoveField(
            model_name='category',
            name='duration_consultation',
        ),
        migrations.RemoveField(
            model_name='category',
            name='online_consultation',
        ),
        migrations.RemoveField(
            model_name='category',
            name='personal_consultation',
        ),
        migrations.AlterField(
            model_name='category',
            name='direction',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='education',
            name='skill',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='cabinet',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='couple_consultation_duration',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Длительность консультации для пар'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='duration_consultation',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Длительность консультации'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='experience',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='online_consultation',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Онлайн-консультация'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='personal_consultation',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Личная встреча'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='surname',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Город'),
        ),
    ]
