# Generated by Django 4.0.3 on 2022-03-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_remove_category_couple_consultation_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='direction',
        ),
        migrations.AddField(
            model_name='employer',
            name='direction',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='employer.category', verbose_name='Направление'),
        ),
    ]
