# Generated by Django 4.0.3 on 2022-03-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_remove_employer_direction_employer_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
    ]
