# Generated by Django 4.0.3 on 2022-03-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_employer_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='education',
        ),
        migrations.AddField(
            model_name='employer',
            name='education',
            field=models.ManyToManyField(blank=True, null=True, related_name='education', to='employer.education', verbose_name='Образование'),
        ),
    ]
