# Generated by Django 4.0.3 on 2022-03-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_remove_employer_education_employer_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ['cabinet'],
            },
        ),
        migrations.RemoveField(
            model_name='employer',
            name='cabinet',
        ),
        migrations.AddField(
            model_name='employer',
            name='cabinet',
            field=models.ManyToManyField(blank=True, null=True, related_name='adress', to='employer.adress', verbose_name='Кабинет'),
        ),
    ]
