# Generated by Django 4.0.3 on 2022-03-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0012_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рождение'),
        ),
    ]
