# Generated by Django 4.0.3 on 2022-03-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0015_application_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-date'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
